tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "yqrashawn/goku"
tap "aws/tap"
tap "koekeishiya/formulae"
tap "cmacrae/formulae"

##################


cask "font-fira-code"
cask "font-fontawesome"

brew "yqrashawn/goku/goku"
cask "alfred"
cask "karabiner-elements"
cask "keyboard-maestro"
cask "iterm2"
cask "lulu"
cask "transmission"
cask "spotify"
cask "onedrive"
cask "kap"
cask "keybase"
cask "obs"
cask "vlc"
# cask "1password" -- Install it from website

cask "notion"
cask "obsidian"

cask "visual-studio-code"
cask "altair-graphql-client"

cask "discord"
cask "telegram-desktop"
cask "slack"
cask "zoomus"
cask "loopback"
cask "inkscape"

# CLI

brew "ag"
brew "awscli"
brew "aws-sam-cli"
brew "bat"
brew "cmake"
brew "git"
brew "ripgrep"
brew "ispell"
brew "coreutils"
brew "fd"
brew "neovim"
brew "pyenv"
brew "node"
brew "openjdk"
brew "haskell-stack"
brew "z"     # Autojumping tool
