tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "yqrashawn/goku"
tap "candid82/brew"
tap "aws/tap"
tap "koekeishiya/formulae"
tap "cmacrae/formulae"



##################
#                #
# NON-FREE       #
#                #
##################
cask "spotify"
cask "1password"
cask "visual-studio-code"
cask "discord"
cask "telegram-desktop"
cask "slack"
cask "zoom"
cask "loopback"
cask "loom"
cask "skitch"
cask "parsec"



##################
#                #
# WINDOW MGMT    #
#                #
##################
brew "yqrashawn/goku/goku"
cask "karabiner-elements"
cask "hammerspoon"



##################
#                #
# MULTIMEDIA     #
#                #
##################
cask "obs"
cask "vlc"
cask "brave-browser"
cask "selfcontrol"



##################
#                #
# USEFUL APPS    #
#                #
##################

# Term emulator
cask "iterm2"

# Git + LFS
brew "git"
brew "git-lfs"

# The Silver Searcher
brew "ag"

# Like find | grep, but better
brew "ripgrep"

# GNU Utils for MacOS
brew "coreutils"

# Hyperextensible Vim-based text editor
brew "neovim"

# Autojumping tool
brew "z"

# OCR
brew "tesseract"




##################
#                #
# BOOSTER DEV    #
#                #
##################
brew "awscli"
cask "insomnia"



##################
#                #
# PROG LANGS     #
#                #
##################
brew "nvm"
brew "python@3.8"
