#!/usr/bin/env sh

# Big Sur fix - remember to add yourself to the sudoers like described in the wiki
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config status_bar                   on
yabai -m config status_bar_background_color  0xff0a0a0a
yabai -m config status_bar_foreground_color  0xff0a0a0a

yabai -m config active_window_border_topmost on

yabai -m config layout bsp
yabai -m config window_placement second_child
yabai -m config top_padding    50
yabai -m config bottom_padding 20
yabai -m config left_padding   20
yabai -m config right_padding  20
yabai -m config window_gap     20

yabai -m config focus_follows_mouse autofocus

yabai -m config window_border on
yabai -m config window_border_width 4
yabai -m config active_window_border_color   0xff0a0a0a
yabai -m config normal_window_border_color   0xff1a1a1a
yabai -m config insert_window_border_color   0xff1a1a1a

yabai -m config split_ratio 0.5

yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.97
yabai -m config window_shadow off

for i in {1..8}; do  # Create 8 spaces on startup, as we got already 1
  yabai -m space
done