#!/usr/bin/env sh

spacebar -m config position           top
spacebar -m config height             26
spacebar -m config spacing_left       25
spacebar -m config spacing_right      15
spacebar -m config text_font          "Fira Code:Regular:12.0"
spacebar -m config icon_font          "Font Awesome 5 Free:Solid:12.0"
spacebar -m config background_color   0xff2e3440
spacebar -m config foreground_color   0xffeceff4
spacebar -m config space_icon_color   0xff8fbcbb
spacebar -m config power_icon_color   0xffebcb8b
spacebar -m config battery_icon_color 0xffa3be8c
spacebar -m config dnd_icon_color     0xffb48ead
spacebar -m config clock_icon_color   0xff5e81ac
spacebar -m config space_icon_strip      4 5     
spacebar -m config power_icon_strip    
spacebar -m config space_icon         
spacebar -m config clock_icon         
spacebar -m config dnd_icon           
spacebar -m config clock_format       "%d/%m - %R"

echo "spacebar configuration loaded.."